### ISSUE TITLE
Spell support for Documentation sections

### ISSUE THREAD

**Issue by mtihlenfield** [Hubro/tree-sitter-robot#8]
It would be really nice to have spell support for keyword and module documentation. For example:

```
*** Settings ***
Documentation    could have spell checking here!

*** Keywords ***
Spell Check Keyword
    [Documentation]    could have spell checking here too!
```

For reference: https://neovim.io/doc/user/treesitter.html#treesitter-highlight-spell

**Comment by mtihlenfield** [comment]
Just realized that you can use variables in Documentation sections, which probably means this won't work.

**Comment by Hubro** [comment]
There's `@spell` and `@nospell`, the latter of which can be used to disable spell checking in interpolated variables. I think this is a good idea.

**Comment by Hubro** [comment]
It might be a bit tricky to actually match the `Documentation` setting. I'm using regex to match it case insensitively, so I don't think this would work: `(setting_statement "Documentation" ...)`.

Changing the grammar to capture the setting name as a separate node, then matching it with the [`match?` predicate](https://neovim.io/doc/user/treesitter.html#treesitter-predicate-match%3F) would probably do the trick. It might even be possible without changing the grammar.

**Comment by Hubro** [comment]
@mtihlenfield Fixed!
